project_id = "wivbtmtgpsxupfjwwovf"

[functions.create-order]
verify_jwt = false

[functions.encrypt-token]
verify_jwt = false

[functions.pushinpay-create-pix]
verify_jwt = false

[functions.pushinpay-get-status]
verify_jwt = false

[functions.pushinpay-webhook]
verify_jwt = true